name: Conventional Commit Check PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint-pr-title:
    permissions:
      pull-requests: read
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/conventional-commits.yml@a69a25679b7d47df1256596f1fc9df0fdc38a8a8 # conventional-commits-v1.2.1
