name: PR test

on: [pull_request]

permissions:
  id-token: write # Required by iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.6.0
  packages: write # Required by iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.6.0
  contents: read

concurrency:
  group: ${{ github.ref }}-pr-test
  cancel-in-progress: true

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run check-format

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run check-types

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

  npm-dry-run:
    uses: ./.github/workflows/reusable-npm.yml
    with:
      dry-run: true
